# Deploying web server 
- name: Deploying web server 
  hosts: node1
  tasks:
   - name: Example of single line format
     file: path=/tmp/test state=directory mode=0777 owner=root group=root


   - name: Exapmle of multiline format
     file: path=/tmp/test
           state=directory
           mode=0777
           owner=root
           group=root


   - name: Example of dictionary format
     file:
       path: /tmp/test
       state: directory
       mode: 0777
       owner: root
       group: rooty

