---
- name: Check Disk Space Usage
  hosts: all
  tasks:
          - name: Disk usage from command module
            command: df -h
            register: space
          - debug:
                  var: space.stdout_lines

- name: Check Memory
  hosts: all
  tasks:
    - name: Hardware info
      vars:
        msg: |
          RAM: "{{ ansible_memtotal_mb }}"
          SWAP: "{{ ansible_memory_mb.swap.total }}"
      debug:
         msg: "{{ msg.split('\n') }}"
~
~
