- name: Example of standard loop
  hosts: node1
  vars:
    mypass: redhat
  tasks:
    - name: add users  
      user: 
        name: "{{ item }}"
        state: present
        password: "{{ mypass | password_hash('sha512')}}"
      with_items:
         - shyam
         - manish
         - ravi
         - natasha

    - name: Copy multiple files
      copy:
         src: "{{ item }}"
         dest: /tmp

      with_items:
         - /etc/passwd
         - /etc/fstab
         - /etc/group

    - name: copies /etc/fstab into /tmp  /root /opt
      copy: 
         src: /etc/fstab
         dest: "{{ item }}"
  
      with_items:
         - /root
         - /opt
         - /tmp
