- hosts: node1
  user: ansible
  become: true
  become_method: sudo
  become_user: root
  
  gather_facts: false
  tasks:
   - file:
       path: /tmp/test
       state: directory
       mode: 0777
       owner: ansible
       group: wheel


   - copy:
       src: /etc/fstab
       dest: /tmp/test


   - service:
       name: crond
       state: restarted

  
